### PR TITLE
[WIP] Use astunparse to recover the traits definition

### LINKED ISSUE #9: Comments inside traits definitions are not ignored
It would be nice if comments inside definitions are not ignored. 

Currently the `get_trait_definition` function will also return traits.
```
trait_1 = Float  # comment
```

This results in unattractive rst.

### PR DESCRIPTION
**Pull request by itziakos**
Attempt to fix #9

### CODE REVIEW

**Comment by rkern** [comment]
Sphinx should not be a dependency of Traits.

**Comment by itziakos** [comment]
> Sphinx should not be a dependency of Traits.

That is correct but it is a dependency for the trait_documenter package (a separate package that I am extracting out of traits).

**Comment by itziakos** [comment]
While this PR works with python 2.6, I still do not like that I have to monkey path `astor`. It would be nice if `to_source` supported an option to special case python 2.6. I need to think about it.

**Comment by rkern** [comment]
D'oh! Sorry, I missed the context. I thought this was a followon to the `traits` modifications @stefanoborini was making.

**Comment by itziakos** [comment]
No problem.

**Comment by itziakos** [comment]
close infavor of #11

**Pull request closed without merging**
